version: '3'
services:
  filefly:
    image: 3rtdevops/filefly:latest
    environment:
      USERNAME: "admin"
      PASSWORD: 'P@ssW0rd!'
      SECRET_KEY: '' # 32 character string alpha-num - If not set it will auto generate
    ports:
    # Filefly Port
      - "8052:8000"
    volumes:
      - /home/user/filefly/data:/data
      - /home/user/filefly/sqllite:/sql
