name: Test and Publish Filefly

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker test container
      run: docker build -t madeofpendletonwool/filefly-test . -f dockerfile-test

    - name: Run tests in the Docker container
      run: docker run madeofpendletonwool/filefly-test

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_KEY }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/filefly # Replace with your Docker Hub username and image name

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./dockerfile # Adjust if your Dockerfile has a different path
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}