name: Test Filefly

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker test container
      run: docker build -t madeofpendletonwool/filefly-test . -f dockerfile-test

    - name: Run tests in the Docker container
      run: docker run madeofpendletonwool/filefly-test
